apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cron-set-controller.fullname" . }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cron-set-controller
    app.kubernetes.io/part-of: cron-set-controller
    control-plane: controller-manager
    {{- include "cron-set-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "cron-set-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        {{- include "cron-set-controller.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - name: kube-rbac-proxy
        args:
        - --secure-listen-address=0.0.0.0:{{ .Values.metricsService.port }}
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: {{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.metricsService.port }}
          name: https
          protocol: TCP
        resources: {{- toYaml .Values.kubeRbacProxy.resources | nindent 10 }}
        {{- with .Values.kubeRbacProxy.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: manager
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        - name: NODE_IDENTIFICATION_KEY
          value: {{ .Values.manager.env.nodeIdentificationKey }}
        image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.manager.resources | nindent 10 }}
        {{- with .Values.manager.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "cron-set-controller.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
