apiVersion: v1
kind: Service
metadata:
  name: {{ include "cron-set-controller.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cron-set-controller
    app.kubernetes.io/part-of: cron-set-controller
    control-plane: controller-manager
    {{- include "cron-set-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "cron-set-controller.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.metricsService.port }}
    targetPort: https
    protocol: TCP
    name: https
