apiVersion: batch.grasse.io/v1alpha1
kind: CronSet
metadata:
  labels:
    app.kubernetes.io/name: cron-set-controller
    app.kubernetes.io/managed-by: kustomize
  name: cronset-sample
spec:
  # TODO(user): Add fields here
