name: Build-Push Image

on:
  push:
    tags:
      - 'cron-set-controller-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: grasse
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Generate Image Tag
        id: tag
        run: |
          TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          IMAGE_VERSION=$(echo "$TAG" | sed 's/cron-set-controller-v//')
          IMAGE_TAG="ghcr.io/grasse-oss/cron-set-controller:${IMAGE_VERSION}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tag.outputs.image_tag }}
