name: Build-Push Image

on:
  push:
    branches:
      - 'ci/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Generate tag name
        id: tag
        run: |
          # IMAGE_TAG="ghcr.io/grasse-oss/cron-set-controller:"${GITHUB_REF#refs/tags/v}"
          IMAGE_TAG="ARAR"
          echo "::set-output name=image_tag::${IMAGE_TAG}"

      - name: Build and Push Image
        run: |
          cat "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u grasse --password-stdin
          make docker-build docker-push IMG=${IMAGE_TAG}
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}