name: Unit Test

on:
  push:
    branches:
      - 'main'
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
      - 'test/**'

jobs:
  jobs:
    unit-tests:
      runs-on: ubuntu-latest
      name: Unit tests
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            go-version: '^1.20.2'
        - run: make test